services:
  plumber-api:
    build: ./cat-api-adaptive
    image: catapiicmc/plumber-cat-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - cat-api

  django-api:
    build: ./cat-api-django
    image: catapiicmc/django-cat-api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      plumber-api:
        condition: service_started
    networks:
      - cat-api

  cat-app:
    build:
      context: ./cat-app
      dockerfile: dockerfile
    image: catapiicmc/cat-app
    ports:
      - "3000:3000"
    depends_on:
      django-api:
        condition: service_started
    networks:
      - cat-api

networks:
  cat-api:
    driver: bridge
    name: cat-api
